// Ambient declaration for `.deca` single-file components.
//
// This is a COMMITTED, hand-written `.d.ts` shipped as-is (see the "types/"
// entry in package.json "files" and exports["./deca"]). It is intentionally
// NOT generated by `tsc`:
//   - `tsc` never copies a hand-written `.d.ts` from `src/` into `dist/`, and
//   - the build sets `moduleDetection: "force"`, which would turn a `.ts`
//     version of this file into a module and make `declare module "*.deca"`
//     an illegal augmentation (TS2664).
// A plain `.d.ts` sidesteps both problems: it is exempt from module detection,
// so the `*.deca` wildcard is declared ambiently and globally.
//
// Consumers opt in via `"types": ["decagrammaton/deca"]` in their tsconfig,
// which registers the wildcard so `import Foo from "./Foo.deca"` typechecks
// against the module's `compile`/`toComponent` shape.

declare module "*.deca" {
  const mod: import("decagrammaton").DecaModule;
  export default mod;
}
